name: bmi_calculater
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  font_awesome_flutter: ^9.2.0
  flutter_neumorphic: ^3.2.0
  cupertino_icons: ^1.0.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true


  assets:
    - images/page1.jpg
    - images/page2.png
 
  fonts:
    - family: dana
      fonts:
        - asset: fonts\dm.ttf
  